#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Mac 微信数据导出工具 - 打包脚本

用法:
    python3 build_mac_app.py          # 生成 spec 并打包
    python3 build_mac_app.py spec     # 只生成 spec，不打包
    python3 build_mac_app.py clean    # 清理构建产物
"""

import os
import shutil
import sys
from pathlib import Path

__version__ = "3.0.0"
ROOT = Path(__file__).parent.resolve()


def _datas():
    """收集需要打包进去的数据文件，只包含实际存在的目录"""
    candidates = [
        ("app/resources", "app/resources"),
        ("app/decrypt/version_list.json", "app/decrypt"),
        ("pywxdump", "pywxdump"),
        ("resource/datasets", "resource/datasets"),
        ("resource/render/templates", "resource/render/templates"),
    ]
    result = []
    for src, dst in candidates:
        if (ROOT / src).exists():
            result.append((src, dst))
    return result


def _icon_arg():
    """返回 icon 参数，如果 icon.icns 不存在则跳过"""
    icon_path = ROOT / "icon.icns"
    if icon_path.exists():
        return f"icon='icon.icns',"
    return "# icon not found, skipped"


def create_spec():
    """生成 PyInstaller spec 文件"""
    datas_lines = "\n        ".join(
        f"('{src}', '{dst}')," for src, dst in _datas()
    )

    spec_content = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_mac_app.py v{__version__}

block_cipher = None

a = Analysis(
    ['wxdump_mac_main.py'],
    pathex=['{ROOT}'],
    binaries=[],
    datas=[
        {datas_lines}
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'dbutils',
        'dbutils.pooled_db',
        'sqlite3',
        'lz4',
        'lz4.frame',
        'lz4.block',
        'PIL',
        'PIL.Image',
        'jieba',
        'flask',
        'flask.templating',
        'jinja2',
        'requests',
        'docx',
        'docx.oxml',
        'protobuf',
        'google.protobuf',
        'Crypto',
        'Crypto.Cipher',
        'Crypto.Cipher.AES',
        'json',
        'csv',
        'pathlib',
        'subprocess',
        'threading',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['pywin32', 'pymem', 'win32api', 'win32con'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='WeChatExporter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    {_icon_arg()}
)

app = BUNDLE(
    exe,
    name='WeChatExporter.app',
    {_icon_arg()}
    bundle_identifier='com.wechat.exporter.mac',
    info_plist={{
        'CFBundleName': 'WeChatExporter',
        'CFBundleDisplayName': 'Mac 微信数据导出工具',
        'CFBundleVersion': '{__version__}',
        'CFBundleShortVersionString': '{__version__}',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '10.13.0',
        'NSAppleEventsUsageDescription': 'This app needs to control other apps for WeChat data export.',
    }},
)
"""
    spec_path = ROOT / "wxdump_mac.spec"
    spec_path.write_text(spec_content, encoding="utf-8")
    print(f"✅ spec 文件已生成: {spec_path}")
    return spec_path


def check_pyinstaller():
    try:
        import PyInstaller
        print(f"✅ PyInstaller {PyInstaller.__version__}")
        return True
    except ImportError:
        print("❌ PyInstaller 未安装，请运行: pip3 install pyinstaller")
        return False


def build():
    if not check_pyinstaller():
        sys.exit(1)

    spec_path = create_spec()

    cmd = f'pyinstaller --clean --noconfirm "{spec_path}"'
    print(f"\n🔨 执行打包: {cmd}\n")
    ret = os.system(cmd)

    if ret == 0:
        app_path = ROOT / "dist" / "WeChatExporter.app"
        print(f"\n{'='*60}")
        print("🎉 打包成功！")
        print(f"   应用位置: {app_path}")
        print("\n使用方法:")
        print("   双击 WeChatExporter.app 启动")
        print("   或拖到 /Applications 文件夹")
        print(f"{'='*60}")
    else:
        print("\n❌ 打包失败，请检查上方错误信息")
        sys.exit(1)


def clean():
    for name in ["build", "dist", "wxdump_mac.spec", "__pycache__"]:
        p = ROOT / name
        if p.exists():
            if p.is_dir():
                shutil.rmtree(p)
            else:
                p.unlink()
            print(f"🗑️  已删除: {p}")
    print("✅ 清理完成")


def main():
    print("=" * 60)
    print(f"Mac 微信数据导出工具 - 打包脚本 v{__version__}")
    print("=" * 60)

    if not (ROOT / "app").exists() or not (ROOT / "scripts").exists():
        print("❌ 请在项目根目录运行此脚本")
        sys.exit(1)

    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"

    if cmd == "clean":
        clean()
    elif cmd == "spec":
        create_spec()
    elif cmd == "build":
        build()
    else:
        print(f"未知命令: {cmd}")
        print("用法: python3 build_mac_app.py [build|spec|clean]")
        sys.exit(1)


if __name__ == '__main__':
    main()
