#!/usr/bin/env python3
import argparse
import json
import sqlite3
from pathlib import Path

from mac_decrypt_wcdb_raw import decrypt_db


def is_sqlite_ok(path: Path) -> bool:
    try:
        with sqlite3.connect(path) as conn:
            row = conn.execute("pragma integrity_check").fetchone()
        return bool(row and row[0] == "ok")
    except sqlite3.Error:
        return False


def load_candidates(path: Path) -> tuple[Path, list[dict]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    db_root = Path(payload["db_root"]).expanduser()
    candidates = payload.get("candidates", [])
    return db_root, candidates


def choose_key_by_path(candidates: list[dict]) -> dict[str, str]:
    keys: dict[str, str] = {}
    for candidate in candidates:
        key = str(candidate.get("key", "")).lower()
        if len(key) != 64:
            continue
        for rel in candidate.get("paths", []):
            keys.setdefault(rel, key)
    return keys


def main() -> int:
    parser = argparse.ArgumentParser(description="Batch decrypt macOS WeChat 4.x WCDB databases from LLDB key candidates.")
    parser.add_argument("--keys", default="/tmp/wechat_lldb_key_candidates.json", help="JSON generated by scripts/lldb_scan_wechat_keys.py.")
    parser.add_argument("--db-root", help="Override encrypted db_storage root.")
    parser.add_argument("--output", default="app/Database/MacMsg", help="Output directory for decrypted SQLite databases.")
    parser.add_argument("--verify", action="store_true", help="Run pragma integrity_check after each decrypt.")
    args = parser.parse_args()

    discovered_root, candidates = load_candidates(Path(args.keys).expanduser())
    db_root = Path(args.db_root).expanduser() if args.db_root else discovered_root
    output_root = Path(args.output).expanduser()
    path_to_key = choose_key_by_path(candidates)

    if not path_to_key:
        print("No usable key candidates found.")
        return 2

    ok = 0
    failed = 0
    for rel, key in sorted(path_to_key.items()):
        input_path = db_root / rel
        output_path = output_root / rel
        if not input_path.exists():
            print(f"skip missing: {rel}")
            continue
        try:
            decrypt_db(key, input_path, output_path)
            if args.verify and not is_sqlite_ok(output_path):
                failed += 1
                print(f"failed integrity_check: {rel}")
                continue
            ok += 1
            print(f"decrypted: {rel}")
        except Exception as exc:
            failed += 1
            print(f"failed: {rel}: {exc}")

    print(f"done decrypted={ok} failed={failed} output={output_root.resolve()}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
